stages:
  - build

build-debian-linux-gcc:
  image: gcc
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install tzdata
    - apt -y install make cmake pkg-config libusb-1.0-0-dev
  script:
    - cd examples/posix && mkdir build && cd build && cmake .. && CC=gcc make -j

build-debian-linux-clang:
  image: gcc
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt -y install tzdata
    - apt -y install clang
    - apt -y install make cmake pkg-config libusb-1.0-0-dev
  script:
    - cd examples/posix && mkdir build && cd build && cmake .. && CC=clang make -j

build-esp-idf-5.4:
  image: espressif/idf:release-v5.4
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  before_script:
    - pushd .
    - cd external/btstack
    - git apply ../patches/*.patch
    - cd port/esp32
    - IDF_PATH=../../../../src/ ./integrate_btstack.py
    - popd
  script:
    - cd examples/esp32
    - idf.py build
