name: Build with ESP-IDF v5.4

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Patch BTStack
      shell: bash
      run: cd external/btstack && git apply ../patches/*.patch

    - name: Install BTStack
      shell: bash
      run: cd external/btstack/port/esp32 && IDF_PATH=../../../../src/ ./integrate_btstack.py

    - name: Unijoysticle build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_unijoysticle -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_unijoysticle" build'

    - name: Example ESP32 build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32
        path: 'examples/esp32'
        command: "idf.py set-target esp32 && idf.py build"

    - name: Example ESP32-S3 build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32-s3
        path: 'examples/esp32'
        command: "idf.py set-target esp32s3 && idf.py build"

    - name: Example ESP32-C3 build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32-c3
        path: 'examples/esp32'
        command: "idf.py set-target esp32c3 && idf.py build"

    - name: Example ESP32-C6 build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32-c6
        path: 'examples/esp32'
        command: "idf.py set-target esp32c6 && idf.py build"

    - name: Example ESP32-H2 build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.4
        target: esp32-h2
        path: 'examples/esp32'
        command: "idf.py set-target esp32h2 && idf.py build"


